### ISSUE TITLE
(ToDo) ORE GEN

### ISSUE THREAD

**Issue by Vaygrim** [GrimCo/CoopLife2#19]
Ore Gen needs a total overhaul, specifically due to the shuffling of mods in the pack.

- [x] Check for duplicate ores (Copper, Tin, Lead, etc)
- [x] Move all ore-gen to COFH-Core
- [x] Coal (Y-1 to Y-75)
- [x] Iron (Y-1 to Y-60)
- [x] Copper / Tin (Y-30 to Y-60)
- [x] Gold / Redstone / Lapis / Diamond / Emerald (Y-1 to Y-30)
- [x] Silver / Lead / Nickel (Y-1 to Y-30)
- [x] No Iridium Ore on starter planet

Anything else comes up, ask and we can figure out what to do.

**Comment by XEridaniTribalX** [comment]
### As of V0.6 of CL2, these are what ores are in the pack:
**Vanilla:** Iron, Gold, Coal, Lapis, Emerald, Redstone, Nether Quartz
**AA:** Black Quartz
**BOP:** Ender Amethyst, Ruby, Peridot, Topaz, Tanzanite, Malachite, Sapphire, Amber
**Forestry:** Apatite, Copper, Tin
**RFTools:** Dimensional Shard
**TechReborn:** Galena, Iridium, Ruby, Sapphire, Bauxite, Pyrite, Cinnabar, Sphalerite, Tungsten, Sheldonite, Peridot, Sodalite, Lead, Silver, Copper, Tin
**Thermal:** Copper, Tin, Silver, Lead, Aluminum, Nickel, Platinum, Iridium, Mana, Oil Sand/Shale, Destabilized Redstone, Energized Netherrack, Resonant End
**Vulpes:** Dilithium, Copper, Tin, Rutile, Aluminum, Iridium

### Here's what it would look like with all of the extra ores cleared out:
**Vanilla:** Iron, Gold, Coal, Lapis, Emerald, Redstone, Nether Quartz
**AA:** Black Quartz
**Forestry:** Apatite
**RFTools:** Dimensional Shard
**TechReborn:** Ruby, Sapphire, Sphalerite, Tungsten, Peridot
**Thermal:** Copper, Tin, Silver, Lead, Aluminum, Nickel, Platinum, Iridium, Mana, Oil Sand/Shale, Destabilized Redstone, Energized Netherrack, Resonant End
**Vulpes:** Dilithium, Rutile

We can clear this up more as we go on. It was also suggested that we add ores for the Red and Yellow Garnets, as well as Cheese ore for the Moon. So here's a list of some custom ores we may want:
1. Ender Pearl Ore (from Wasted)
2. Red Garnet Ore
3. Yellow Garnet Ore
4. Cheese Ore

**Comment by Vaygrim** [comment]
Moved most of Ore Gen over to COFH
https://github.com/GrimCo/CoopLife2/commit/82b79decea1af533f3f44e3014b1b8bd13076ec2

Part 2 will be TechReborn and Advanced Rocketry / Vulpes. I need more ore rarity numbers / feedback for those mods first however. Also I think we still need to define some non-Overworld planets to put some of this stuff on as well.

(Example: We were going to put Dilithium out on another planet, yes?)

**Comment by Vaygrim** [comment]
For now I'm calling this "Done", but I want to keep the issue option until after Minefaire Houston so we can double check everything and update ore-gen in asteroids and other planets.

**Comment by mallrat208** [comment]
Some thoughts since playing with this on the test server

Apatite is very rare and found very low compared to normal. Granted we normally get WAY too much of it with the default amounts, I think it should be moved upwards a (say to  60~80) and the recipe to convert Apatite to Fertilizer should have an increased yield to compensate for the reduced ore found in world.

**Comment by Vaygrim** [comment]
Sounds good. Do you want to go ahead and make the changes?

**Comment by Vaygrim** [comment]
Corrected Apatite ore-gen cluster numbers, and raised the generation height up to the Y-32 to Y-72 range.
